{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if $attribute.content}
<a target="_blank" href={concat( 'content/download/', $attribute.contentobject_id, '/', $attribute.id,'/version/', $attribute.version , '/file/', $attribute.content.original_filename|urlencode )|ezurl}>lees meer</a>
<p>
{"Download count"|i18n("i18n('cjw_newsletter/datatype/ezbinaryfiletype')}: {$attribute.content.download_count|wash}
</p>
{/if}
